package com.medical.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.medical.dao.UsersDao;
import com.medical.dao.infoTypeDao;
import com.medical.dao.infosDao;
import com.medical.dao.AreasDao;
import com.medical.dao.StudentsDao;
import com.medical.dao.TeachersDao;
import com.medical.dao.stuAndteaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 5): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 5;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UsersDao.createTable(db, ifNotExists);
        infoTypeDao.createTable(db, ifNotExists);
        infosDao.createTable(db, ifNotExists);
        AreasDao.createTable(db, ifNotExists);
        StudentsDao.createTable(db, ifNotExists);
        TeachersDao.createTable(db, ifNotExists);
        stuAndteaDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UsersDao.dropTable(db, ifExists);
        infoTypeDao.dropTable(db, ifExists);
        infosDao.dropTable(db, ifExists);
        AreasDao.dropTable(db, ifExists);
        StudentsDao.dropTable(db, ifExists);
        TeachersDao.dropTable(db, ifExists);
        stuAndteaDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UsersDao.class);
        registerDaoClass(infoTypeDao.class);
        registerDaoClass(infosDao.class);
        registerDaoClass(AreasDao.class);
        registerDaoClass(StudentsDao.class);
        registerDaoClass(TeachersDao.class);
        registerDaoClass(stuAndteaDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
